-- ════════════════════════════════════════════════════════════════════
-- ПРОЯВ — Міграція адмінки/обліку (Supabase / PostgreSQL)
-- Адаптовано зі структури звітності CopyLounge під специфіку Прояв.
-- Безпечно запускати повторно (IF NOT EXISTS / ON CONFLICT).
-- Запуск: Supabase → SQL Editor → вставити → Run.
-- ════════════════════════════════════════════════════════════════════

-- ── 1. Витрати ──────────────────────────────────────────────────────
create table if not exists expenses (
  id         bigint generated by default as identity primary key,
  date       date    not null,
  -- Категорії під Прояв: Матеріали (конверти/папір/чорнило), Доставка (НП),
  -- Оренда, Маркетинг, Комісія фотографу, Підписки, Зарплата (собі), Інше
  category   text    not null default 'Інше',
  descr      text    default '',
  amount     numeric not null check (amount >= 0),
  payment    text    default 'Готівка',     -- Готівка / Картка
  note       text    default '',
  created_at timestamptz default now()
);
create index if not exists idx_expenses_date on expenses(date);

-- ── 2. Склад матеріалів ─────────────────────────────────────────────
create table if not exists inventory (
  id         bigint generated by default as identity primary key,
  name       text    not null,
  unit       text    default 'шт',          -- шт / рулон / компл / аркуш
  qty        numeric default 0,             -- поточний залишок
  min_qty    numeric default 0,             -- поріг "пора замовити"
  note       text    default '',
  updated_at timestamptz default now()
);

-- Журнал руху складу (прихід / списання / коригування)
create table if not exists inventory_log (
  id         bigint generated by default as identity primary key,
  item_id    bigint  not null references inventory(id) on delete cascade,
  delta      numeric not null,              -- + прихід, - списання
  reason     text    default '',            -- Закупівля / Списання / Коригування
  date       date    default current_date,
  created_at timestamptz default now()
);

-- ── 3. Налаштування (key/value) ─────────────────────────────────────
create table if not exists settings (
  key   text primary key,
  value text
);

-- Цілі Прояв із фінмоделі: особиста ЗП 40–50к → виручка ~45к ціль;
-- постійні витрати ≈2500/міс (частка оренди друкарні, матеріали-резерв)
insert into settings (key, value) values
  ('monthly_target', '45000'),
  ('weekly_target',  '11000'),
  ('fixed_costs',    '2500'),
  ('commission_pct', '12'),       -- % комісії фотографу за замовчуванням
  ('opening_cash',   '0'),
  ('opening_card',   '0'),
  ('opening_date',   '')
on conflict (key) do nothing;

-- ── 4. Розширення orders для звітності прибутку ─────────────────────
-- Фактична собівартість конкретного замовлення (матеріали + комісія),
-- + дати оплати/відправки для аналітики лійки.
alter table orders add column if not exists cost      numeric default 0;
alter table orders add column if not exists paid_at   timestamptz;
alter table orders add column if not exists shipped_at timestamptz;

-- ── 4b. product_type МОЖЕ бути NULL ─────────────────────────────────
-- Роздрібні (à la carte) замовлення не мають набору → product_type = null.
-- Зайвий NOT NULL валив усі роздрібні вставки («null value ... violates
-- not-null constraint»). Знімаємо обмеження.
alter table orders alter column product_type drop not null;

-- ── 6. Telegram-сповіщення фотографу (MARKETING_CONTEXT 8.4) ────────
-- tg_chat_id    — куди слати пінг «вашого клієнта оплачено» (set через webhook).
-- tg_link_token — стабільний токен у deep-link t.me/<bot>?start=<token>, за яким
--                 webhook знаходить фотографа й прив'язує його chat_id.
alter table photographers add column if not exists tg_chat_id    text;
alter table photographers add column if not exists tg_link_token text;
create unique index if not exists idx_photographers_tg_link_token
  on photographers(tg_link_token) where tg_link_token is not null;

-- ── 7. Кабінет клієнта: акаунти + архів кадрів (нічого не губиться) ──
-- Клієнт реєструється наприкінці замовлення (телефон + пароль); усі його
-- замовлення (за нормалізованим телефоном) прив'язуються до акаунта.
create table if not exists clients (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  phone         text not null unique,        -- нормалізований: лише цифри
  instagram     text,
  email         text,
  password_hash text not null,
  created_at    timestamptz default now()
);
alter table orders add column if not exists client_id uuid references clients(id);
create index if not exists idx_orders_client on orders(client_id);

-- Реєстр кадрів замовлення. Самі файли — у Cloudflare R2 (binding PHOTOS),
-- тут лише ключі. Прив'язка за токеном замовлення (натуральний ключ усіх флоу).
create table if not exists order_photos (
  id          bigint generated by default as identity primary key,
  order_token text not null,
  storage_key text not null,
  color       text,
  paper       text,
  qty         int  default 1,
  created_at  timestamptz default now()
);
create index if not exists idx_order_photos_token on order_photos(order_token);

-- ── 5. Стартові позиції складу під Прояв ────────────────────────────
insert into inventory (name, unit, qty, min_qty, note) values
  ('Оксамитові конверти latte',            'шт',    0, 5,  'Малий/середній набір'),
  ('Оксамитові конверти айворі (ведмедик)', 'шт',    0, 5,  'Лінійка «Малюк»'),
  ('Преміальні коробки',                   'шт',    0, 3,  'Великий набір'),
  ('Фотопапір 10×15 (рулон)',              'рулон', 0, 1,  '≈650 фото з рулона 152мм'),
  ('Чорнило (набір CMYK)',                 'компл', 0, 1,  ''),
  ('Картки-вкладки з текстом',             'шт',    0, 20, ''),
  ('Калька',                               'аркуш', 0, 20, '')
on conflict do nothing;
