-- ════════════════════════════════════════════════════════════════════
-- ПРОЯВ — Міграція адмінки/обліку (Supabase / PostgreSQL)
-- Адаптовано зі структури звітності CopyLounge під специфіку Прояв.
-- Безпечно запускати повторно (IF NOT EXISTS / ON CONFLICT).
-- Запуск: Supabase → SQL Editor → вставити → Run.
-- ════════════════════════════════════════════════════════════════════

-- ── 1. Витрати ──────────────────────────────────────────────────────
create table if not exists expenses (
  id         bigint generated by default as identity primary key,
  date       date    not null,
  -- Категорії під Прояв: Матеріали (конверти/папір/чорнило), Доставка (НП),
  -- Оренда, Маркетинг, Комісія фотографу, Підписки, Зарплата (собі), Інше
  category   text    not null default 'Інше',
  descr      text    default '',
  amount     numeric not null check (amount >= 0),
  payment    text    default 'Готівка',     -- Готівка / Картка
  note       text    default '',
  created_at timestamptz default now()
);
create index if not exists idx_expenses_date on expenses(date);

-- ── 2. Склад матеріалів ─────────────────────────────────────────────
create table if not exists inventory (
  id         bigint generated by default as identity primary key,
  name       text    not null,
  unit       text    default 'шт',          -- шт / рулон / компл / аркуш
  qty        numeric default 0,             -- поточний залишок
  min_qty    numeric default 0,             -- поріг "пора замовити"
  note       text    default '',
  updated_at timestamptz default now()
);

-- Журнал руху складу (прихід / списання / коригування)
create table if not exists inventory_log (
  id         bigint generated by default as identity primary key,
  item_id    bigint  not null references inventory(id) on delete cascade,
  delta      numeric not null,              -- + прихід, - списання
  reason     text    default '',            -- Закупівля / Списання / Коригування
  date       date    default current_date,
  created_at timestamptz default now()
);

-- ── 3. Налаштування (key/value) ─────────────────────────────────────
create table if not exists settings (
  key   text primary key,
  value text
);

-- Цілі Прояв із фінмоделі: особиста ЗП 40–50к → виручка ~45к ціль;
-- постійні витрати ≈2500/міс (частка оренди друкарні, матеріали-резерв)
insert into settings (key, value) values
  ('monthly_target', '45000'),
  ('weekly_target',  '11000'),
  ('fixed_costs',    '2500'),
  ('commission_pct', '12'),       -- % комісії фотографу за замовчуванням
  ('opening_cash',   '0'),
  ('opening_card',   '0'),
  ('opening_date',   '')
on conflict (key) do nothing;

-- ── 4. Розширення orders для звітності прибутку ─────────────────────
-- Фактична собівартість конкретного замовлення (матеріали + комісія),
-- + дати оплати/відправки для аналітики лійки.
alter table orders add column if not exists cost      numeric default 0;
alter table orders add column if not exists paid_at   timestamptz;
alter table orders add column if not exists shipped_at timestamptz;

-- ── 4b. product_type МОЖЕ бути NULL ─────────────────────────────────
-- Роздрібні (à la carte) замовлення не мають набору → product_type = null.
-- Зайвий NOT NULL валив усі роздрібні вставки («null value ... violates
-- not-null constraint»). Знімаємо обмеження.
alter table orders alter column product_type drop not null;

-- ── 4c. orders.source — дозволити всі реальні напрямки (КРИТИЧНО) ────
-- Старий check-constraint валив вставки: «new row ... violates check
-- constraint "orders_source_check"». Код шле три значення —
-- retail / package / photographer (+ direct на майбутнє). Перевизначаємо
-- обмеження, щоб усі вони були валідні. Заразом дозволяємо NULL (старі рядки).
do $$
begin
  if exists (select 1 from pg_constraint where conname = 'orders_source_check')
  then alter table orders drop constraint orders_source_check;
  end if;
end $$;
alter table orders
  add constraint orders_source_check
  check (source is null or source in ('retail','package','photographer','direct'));

-- ── 6. Telegram-сповіщення фотографу (MARKETING_CONTEXT 8.4) ────────
-- tg_chat_id    — куди слати пінг «вашого клієнта оплачено» (set через webhook).
-- tg_link_token — стабільний токен у deep-link t.me/<bot>?start=<token>, за яким
--                 webhook знаходить фотографа й прив'язує його chat_id.
alter table photographers add column if not exists tg_chat_id    text;
alter table photographers add column if not exists tg_link_token text;
create unique index if not exists idx_photographers_tg_link_token
  on photographers(tg_link_token) where tg_link_token is not null;

-- ── 7. Кабінет клієнта: акаунти + архів кадрів (нічого не губиться) ──
-- Клієнт реєструється наприкінці замовлення (телефон + пароль); усі його
-- замовлення (за нормалізованим телефоном) прив'язуються до акаунта.
create table if not exists clients (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  phone         text not null unique,        -- нормалізований: лише цифри
  instagram     text,
  email         text,
  password_hash text not null,
  created_at    timestamptz default now()
);
alter table orders add column if not exists client_id uuid references clients(id);
create index if not exists idx_orders_client on orders(client_id);

-- Реєстр кадрів замовлення. Самі файли — у Cloudflare R2 (binding PHOTOS),
-- тут лише ключі. Прив'язка за токеном замовлення (натуральний ключ усіх флоу).
create table if not exists order_photos (
  id          bigint generated by default as identity primary key,
  order_token text not null,
  storage_key text not null,
  color       text,
  paper       text,
  qty         int  default 1,
  created_at  timestamptz default now()
);
create index if not exists idx_order_photos_token on order_photos(order_token);

-- ── 8. «Перша серія» (ТЗ ч.2 П1.1): мітка передзамовлень з −15% ─────
-- Сервер ставить true, поки слотів < FIRST_SERIES.slots; лічильник місць
-- на лендінгу читає кількість таких замовлень.
alter table orders add column if not exists first_series boolean default false;

-- ── 9. CRM: аналітика дій + сповіщення клієнтам + профіль клієнта ───
-- first-party трекінг (як FB pixel, але без кук і без передачі третім).
create table if not exists events (
  id         bigint generated by default as identity primary key,
  ts         timestamptz default now(),
  session    text,            -- анонімний id сесії (localStorage), не PII
  type       text not null,   -- pageview | cta_click | format_select | order_start | order_submit | photo_added | ...
  path       text,            -- сторінка
  ref        text,            -- ?ph=<id> / direct / utm-джерело
  meta       jsonb,           -- довільні деталі (без PII)
  client_id  uuid             -- якщо відомий (залогінений клієнт)
);
create index if not exists idx_events_ts      on events(ts desc);
create index if not exists idx_events_type     on events(type);
create index if not exists idx_events_session  on events(session);

-- Сповіщення клієнтам (показуються в кабінеті; авто при зміні статусу + ручні з адмінки).
create table if not exists client_notifications (
  id          bigint generated by default as identity primary key,
  client_id   uuid references clients(id) on delete cascade,
  order_token text,
  title       text,
  body        text,
  kind        text default 'info',   -- info | status | promo
  read        boolean default false,
  created_at  timestamptz default now()
);
create index if not exists idx_cnotif_client on client_notifications(client_id, created_at desc);

-- Профіль клієнта для CRM: нотатки, теги, остання активність.
alter table clients add column if not exists notes     text;
alter table clients add column if not exists tags      text;     -- через кому
alter table clients add column if not exists last_seen timestamptz;

-- ── 10. CRM: журнал дій адміна (audit log) ─────────────────────────
-- Хто що змінив: статуси, виплати, скидання паролів, сповіщення, склад.
create table if not exists audit_log (
  id      bigint generated by default as identity primary key,
  ts      timestamptz default now(),
  actor   text default 'admin',
  action  text not null,   -- order_status | order_edit | payout | client_reset | notify | photographer | expense | inventory | upload
  entity  text,            -- напр. order:ПРЯ-000041 / client:<uuid>
  detail  text             -- людський опис
);
create index if not exists idx_audit_ts on audit_log(ts desc);

-- ── 11. CRM: завдання / нагадування ────────────────────────────────
create table if not exists tasks (
  id         bigint generated by default as identity primary key,
  title      text not null,
  due        date,
  done       boolean default false,
  priority   text default 'normal',   -- low | normal | high
  entity     text,                    -- опц. зв'язок: order:ПРЯ-… / client:<uuid>
  created_at timestamptz default now()
);
create index if not exists idx_tasks_open on tasks(done, due);

-- ── 5. Стартові позиції складу під Прояв ────────────────────────────
insert into inventory (name, unit, qty, min_qty, note) values
  ('Оксамитові конверти latte',            'шт',    0, 5,  'Малий/середній набір'),
  ('Оксамитові конверти айворі (ведмедик)', 'шт',    0, 5,  'Лінійка «Малюк»'),
  ('Преміальні коробки',                   'шт',    0, 3,  'Великий набір'),
  ('Фотопапір 10×15 (рулон)',              'рулон', 0, 1,  '≈650 фото з рулона 152мм'),
  ('Чорнило (набір CMYK)',                 'компл', 0, 1,  ''),
  ('Картки-вкладки з текстом',             'шт',    0, 20, ''),
  ('Калька',                               'аркуш', 0, 20, '')
on conflict do nothing;
